### ISSUE TITLE
macOS 闪退

### ISSUE THREAD

**Issue by netheril96** [hpool-dev/chia-miner#36]
在macOS Big Sur上运行`hpool-miner-chia`报错

```
***************************************************
**** Miner:HPool-Miner-Chia
**** Version:v1.0.5
**** BuildTime:2021-04-21-03:01:27 GMT
**** MinerName:localhost
***************************************************
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4394d53]

goroutine 1 [running]:
github.com/ying32/dylib.(*LazyProc).Call(...)
	vendor/github.com/ying32/dylib/dylib_posix.go:261
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.CreateDiskProver(0xc0005b6280, 0x7f, 0xc00060e090)
	miner/chain/chia/common/chiapos/chiaExternal.go:50 +0x53
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.Open(0xc0005b6280, 0x7f, 0xc0005b6280, 0x7f, 0x4d7f280)
	miner/chain/chia/common/chiapos/chia.go:64 +0xaa
hpool.com/dev/miner-client/miner/chain/chia.(*PlotterSpace).Load(0xc000582360, 0xc000226720, 0x1f)
	miner/chain/chia/plotterSpace.go:99 +0x145
hpool.com/dev/miner-client/miner/chain/chia.NewPlotterSpace(0xc000226720, 0x1f, 0xc000616120, 0xb665c921)
	miner/chain/chia/plotterSpace.go:59 +0x1cf
hpool.com/dev/miner-client/miner/chain/chia.(*Miner).AddPath(0xc000622000, 0xc000226720, 0x1f, 0x4d7da50, 0xc0004c00e0)
	miner/chain/chia/miner.go:164 +0x47
hpool.com/dev/miner-client/miner.(*Wrapper).Start(0xc0002dae10, 0xc000010018, 0x47cf3be)
	miner/wrapper_miner.go:78 +0x190
hpool.com/dev/miner-client/platform.Run(0xc00040ff50, 0xc0003a0600, 0x48a2bf8, 0xc0002dae10)
	platform/console.go:53 +0x628
main.main()
	main.go:83 +0x3de
```

plot文件是用官方1.1.1版生成，而且在官方软件里可以正常farming，所以不应该是plot文件有问题。

**Comment by joslin1215** [comment]
me too

**Comment by wuzhefang** [comment]
me too

**Comment by livmortis** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4394d53]
同样问题，请问解决了吗

**Comment by westerxddd** [comment]
i reversed to chia-miner 1.0.4.1 and it is working on mac os
