### ISSUE TITLE
unexpected signal during runtime execution

### ISSUE THREAD

**Issue by marcchenxiao** [hpool-dev/chia-miner#401]
在linux kernnel  5.4.32  下，总是出现如下致命错误，请问这个可能和什么有关？
 INFO[2021-05-18T10:39:21+08:00] new mining info                               capacity="XXXX TB" file=loggers.go func=logging.CPrint height=297679 jobId=2429425727 line=168 scan consume=365 scan time="2021-05-18 10:39:13" tid=158
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x87c762]

runtime stack:
runtime.throw(0x95426d, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 13 [syscall]:
runtime.cgocall(0x795ed0, 0xc000664ae0, 0x6705451d9de58d00)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc000664ab0 sp=0xc000664a78 pc=0x409bdb
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos._Cfunc_GetQualitiesForChallenge(0x2942980, 0xc0005fedc0, 0xc00020e750, 0x0)
	/var/folders/ky/59p7y1xs3cd6q34r37zlv0gc0000gn/T/go-build1615640014/b146/_cgo_gotypes.go:142 +0x49 fp=0xc000664ae0 sp=0xc000664ab0 pc=0x71dba9
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.GetQualitiesForChallenge.func1(0x2942980, 0xc0005fedc0, 0x20, 0x20, 0xc00020e750, 0x71720a)
	miner/chain/chia/common/chiapos/chia_static.go:44 +0x79 fp=0xc000664b18 sp=0xc000664ae0 pc=0x71fd79
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.GetQualitiesForChallenge(0x2942980, 0xc0005fedc0, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0)
	miner/chain/chia/common/chiapos/chia_static.go:44 +0x9f fp=0xc000664ba0 sp=0xc000664b18 pc=0x71f61f
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.(*File).GetQualitiesForChallenge(0xc00019df40, 0xc0005fedc0, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0)
	miner/chain/chia/common/chiapos/chia.go:210 +0xa9 fp=0xc000664c08 sp=0xc000664ba0 pc=0x71eaa9
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).calcProve(0xc000179880, 0xc0004042d0, 0xc00019df40, 0xc0001780e0)
	miner/chain/chia/prove.go:251 +0x1d4 fp=0xc000664eb8 sp=0xc000664c08 pc=0x73d894
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).checkProve(0xc000179880)
	miner/chain/chia/prove.go:229 +0x165 fp=0xc000664f38 sp=0xc000664eb8 pc=0x73d5e5
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).checkProve-fm()
	miner/chain/chia/prove.go:211 +0x33 fp=0xc000664f50 sp=0xc000664f38 pc=0x73f4d3
github.com/trying2016/common-tools/utils.StartTime.func1(0x927c0, 0xc000013bb0, 0xc000010148)
	vendor/github.com/trying2016/common-tools/utils/timer.go:26 +0x30 fp=0xc000664fc8 sp=0xc000664f50 pc=0x7037f0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000664fd0 sp=0xc000664fc8 pc=0x477821
created by github.com/trying2016/common-tools/utils.StartTime
	vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

goroutine 1 [chan receive, 10 minutes]:
hpool.com/dev/miner-client/platform.Run(0xc000211f50, 0xc000150300, 0x9c8898, 0xc0003aa240)
	platform/console.go:62 +0x7cd
main.main()
	main.go:109 +0x44d

goroutine 9 [select, 10 minutes]:
github.com/trying2016/common-tools/utils.(*Queue).run(0xc000272930)
	vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
	vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 10 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0xc000013b80, 0xc000010140)
	vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
	vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

**Comment by trying2016** [comment]
更新到1.3.0-5版本
https://github.com/hpool-dev/chia-miner/releases

**Comment by marcchenxiao** [comment]
已经更新到1.3.0-5版本，也是同样问题，是不是你们对高版本的kernel不支持呢 ？或者哪里有参数有调整。


我在Linux&nbsp; kernel 3.10上运行没有问题。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hpool-dev/chia-miner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 中午11:00
***@***.***&gt;;
抄送:&nbsp;"/kf ***@***.******@***.***&gt;;
主题:&nbsp;Re: [hpool-dev/chia-miner] unexpected signal during runtime execution (#401)





 
更新到1.3.0-5版本
 https://github.com/hpool-dev/chia-miner/releases

**Comment by trying2016** [comment]
你检查下版本文件是不是正常，-5的版本修复了上面的错误

**Comment by marcchenxiao** [comment]
{1024 1000000}
Rlimit Final {999999 999999}
***************************************************
**** Miner:HPool-Miner-Chia
**** Version:v1.3.0 5
**** BuildTime:2021-05-17-03:26:07 GMT
**** MinerName:linux04
**** ApiKey:c233baba-f39a-4c64-89f9-775d19747aeb
版本如上

**Comment by marcchenxiao** [comment]
https://blog.csdn.net/qq_40267706/article/details/78817614   感觉和这个很类似
