### ISSUE TITLE
HPool-Miner-Chia v1.4.0-2 aarch64 failed to run

### ISSUE THREAD

**Issue by mazhenke** [hpool-dev/chia-miner#499]
My board:
Raspberry Pi 3

{1024 1048576}
Rlimit Final {999999 999999}
failed to rotate: open /home/ubuntu/work/git/hpool/miner/log/miner.log-20210527-27.log_lock: file exists
***************************************************
**** Miner:HPool-Miner-Chia
**** Version:v1.4.0 2
**** BuildTime:2021-05-26-15:00:00 GMT
**** MinerName:HP
**** ApiKey:f1f88a36-5c49-4fc9-ba6e-8b63046f8c90
***************************************************
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2482ff0 pc=0xffff84cc0848]

runtime stack:
runtime.throw(0x97c280, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x54
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x29c

goroutine 1 [syscall]:
runtime.cgocall(0x709208, 0x400015b618, 0x4000136130)
        /usr/local/go/src/runtime/cgocall.go:154 +0x50 fp=0x400015b5e0 sp=0x400015b5a0 pc=0x403d60
os/user._Cfunc_mygetpwuid_r(0x3e8, 0x40001ae9c0, 0x2597060, 0x400, 0x4000136130, 0x200000000)
        /tmp/go-build2748417885/b104/_cgo_gotypes.go:172 +0x44 fp=0x400015b610 sp=0x400015b5e0 pc=0x6815a4
os/user.lookupUnixUid.func1.1(0x3e8, 0x40001ae9c0, 0x4000113b80, 0x4000136130, 0x400015b6c8)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0xc4 fp=0x400015b670 sp=0x400015b610 pc=0x682184
os/user.lookupUnixUid.func1(0x2597001)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0x40 fp=0x400015b6b0 sp=0x400015b670 pc=0x6821f0
os/user.retryWithBuffer(0x4000113b80, 0x400015b7a0, 0x400015b778, 0x4cbf88)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x38 fp=0x400015b710 sp=0x400015b6b0 pc=0x681f38
os/user.lookupUnixUid(0x3e8, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0xcc fp=0x400015b7e0 sp=0x400015b710 pc=0x68194c
os/user.current(0x400015b8d8, 0x4513a8, 0x400015b848)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:49 +0x3c fp=0x400015b820 sp=0x400015b7e0 pc=0x68184c
os/user.Current.func1()
        /usr/local/go/src/os/user/lookup.go:15 +0x20 fp=0x400015b850 sp=0x400015b820 pc=0x682030
sync.(*Once).doSlow(0xc651e0, 0x989fd0)
        /usr/local/go/src/sync/once.go:68 +0x11c fp=0x400015b8b0 sp=0x400015b850 pc=0x47feec
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
os/user.Current(0xc22aa0, 0x95aba0, 0x4000117ad0)
        /usr/local/go/src/os/user/lookup.go:15 +0xfc fp=0x400015b8e0 sp=0x400015b8b0 pc=0x68142c
github.com/trying2016/common-tools/utils.HomePath(0x4000117ad0, 0x400016a460, 0xa, 0x40001333a0)
        vendor/github.com/trying2016/common-tools/utils/path.go:20 +0x20 fp=0x400015b910 sp=0x400015b8e0 pc=0x689d50
github.com/trying2016/common-tools/utils.GetHomePath(0x40001333a0, 0xa, 0x400015b9f8, 0x1)
        vendor/github.com/trying2016/common-tools/utils/path.go:72 +0x20 fp=0x400015b970 sp=0x400015b910 pc=0x68a000
hpool.com/dev/miner-client/miner.(*Wrapper).readMinerId(0x400019a2d0)
        miner/wrapper_miner.go:185 +0xa0 fp=0x400015ba10 sp=0x400015b970 pc=0x6d9480
hpool.com/dev/miner-client/miner.(*Wrapper).Start(0x400019a2d0, 0x4000136008, 0x97ef5d)
        miner/wrapper_miner.go:88 +0x2ac fp=0x400015bbe0 sp=0x400015ba10 pc=0x6d8f1c
hpool.com/dev/miner-client/platform.Run(0x400015bf40, 0x40001023c0, 0x9f11f8, 0x400019a2d0)
        platform/console.go:54 +0x620 fp=0x400015bea0 sp=0x400015bbe0 pc=0x6dc8d0
main.main()
        main.go:109 +0x414 fp=0x400015bf70 sp=0x400015bea0 pc=0x708b84
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x274 fp=0x400015bfd0 sp=0x400015bf70 pc=0x437214
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x400015bfd0 sp=0x400015bfd0 pc=0x46ba54

goroutine 37 [select]:
net/http.(*Transport).getConn(0xc28ca0, 0x4000090040, 0x0, 0x97d58d, 0x5, 0x40000a0048, 0x11, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1368 +0x418
net/http.(*Transport).roundTrip(0xc28ca0, 0x40000a4100, 0xf8, 0x95e040, 0x40001191b8)
        /usr/local/go/src/net/http/transport.go:579 +0x5c4
net/http.(*Transport).RoundTrip(0xc28ca0, 0x40000a4100, 0xc28ca0, 0xc023e37e829b424d, 0x6fdaa3ad9)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x30
net/http.send(0x40000a4000, 0x9e69e8, 0xc28ca0, 0xc023e37e829b424d, 0x6fdaa3ad9, 0xc657e0, 0x0, 0x40000b0008, 0x4000096150, 0x1)
        /usr/local/go/src/net/http/client.go:251 +0x348
net/http.(*Client).send(0x40000960f0, 0x40000a4000, 0xc023e37e829b424d, 0x6fdaa3ad9, 0xc657e0, 0x40000b0008, 0x0, 0x1, 0x96d401)
        /usr/local/go/src/net/http/client.go:175 +0xc8
net/http.(*Client).do(0x40000960f0, 0x40000a4000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:717 +0x33c
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:585
github.com/trying2016/common-tools/utils.(*HttpClient).do(0x4000119be8, 0x96a5cb, 0x4, 0x97d58d, 0x2e, 0x40000a0018, 0x18, 0x18, 0x40000428b8, 0x6d618c, ...)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:278 +0x2d8
github.com/trying2016/common-tools/utils.(*HttpClient).Post(0x4000119be8, 0x97d58d, 0x2e, 0x4, 0x4000098098, 0x0, 0x0, 0x0)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:140 +0xa8
hpool.com/dev/miner-client/miner.(*Wrapper).CheckVersion(0x400019a2d0, 0x400013fd18, 0x0, 0x0, 0x0, 0x0)
        miner/api.go:56 +0x160
hpool.com/dev/miner-client/miner.(*Wrapper).checkVersion(0x400019a2d0)
        miner/wrapper_miner.go:47 +0x70
hpool.com/dev/miner-client/miner.(*Wrapper).Start.func1()
        miner/wrapper_miner.go:71 +0x28
github.com/trying2016/common-tools/utils.SafeGo.func1(0x0, 0x4000113b10)
        vendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x50
created by github.com/trying2016/common-tools/utils.SafeGo
        vendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x44

goroutine 38 [runnable]:
github.com/trying2016/common-tools/utils.(*Queue).run(0x40001ae960)
        vendor/github.com/trying2016/common-tools/utils/queue.go:48
created by github.com/trying2016/common-tools/utils.(*Queue).init
        vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x124

goroutine 39 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0x4000113b30, 0x4000136120)
        vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x8c
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x90

goroutine 40 [runnable]:
github.com/trying2016/common-tools/utils.(*Queue).run(0x40001ae990)
        vendor/github.com/trying2016/common-tools/utils/queue.go:48
created by github.com/trying2016/common-tools/utils.(*Queue).init
        vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x124

goroutine 41 [runnable]:
github.com/trying2016/common-tools/utils.SafeGo.func1(0x9898e8, 0x4000113b50)
        vendor/github.com/trying2016/common-tools/utils/utils.go:165
created by github.com/trying2016/common-tools/utils.SafeGo
        vendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x44

goroutine 42 [runnable]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x927c0, 0x4000113b60, 0x4000136128)
        vendor/github.com/trying2016/common-tools/utils/timer.go:22
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x90

goroutine 20 [select]:
net.(*Resolver).lookupIPAddr(0xc64e20, 0x9ece08, 0x4000092060, 0x96a406, 0x3, 0x40000a0048, 0xd, 0x1bb, 0x0, 0x0, ...)
        /usr/local/go/src/net/lookup.go:299 +0x504
net.(*Resolver).internetAddrList(0xc64e20, 0x9ece08, 0x4000092060, 0x96a406, 0x3, 0x40000a0048, 0x11, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/ipsock.go:280 +0x428
net.(*Resolver).resolveAddrList(0xc64e20, 0x9ece08, 0x4000092060, 0x96a683, 0x4, 0x96a406, 0x3, 0x40000a0048, 0x11, 0x0, ...)
        /usr/local/go/src/net/dial.go:221 +0x3d4
net.(*Dialer).DialContext(0x4000138300, 0x9ece08, 0x4000092060, 0x96a406, 0x3, 0x40000a0048, 0x11, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dial.go:403 +0x180
net/http.(*Transport).dial(0xc28ca0, 0x9ece08, 0x4000092060, 0x96a406, 0x3, 0x40000a0048, 0x11, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1162 +0x178
net/http.(*Transport).dialConn(0xc28ca0, 0x9ece08, 0x4000092060, 0x0, 0x97d58d, 0x5, 0x40000a0048, 0x11, 0x0, 0x40000985a0, ...)
        /usr/local/go/src/net/http/transport.go:1600 +0x155c
net/http.(*Transport).dialConnFor(0xc28ca0, 0x40000be000)
        /usr/local/go/src/net/http/transport.go:1442 +0x90
created by net/http.(*Transport).queueForDial
        /usr/local/go/src/net/http/transport.go:1411 +0x3a8

goroutine 21 [select]:
net.cgoLookupIP(0x9ecd98, 0x40000900c0, 0x96a406, 0x3, 0x40000a0048, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/cgo_unix.go:229 +0x104
net.(*Resolver).lookupIP(0xc64e20, 0x9ecd98, 0x40000900c0, 0x96a406, 0x3, 0x40000a0048, 0xd, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/lookup_unix.go:96 +0x114
net.glob..func1(0x9ecd98, 0x40000900c0, 0x400009a100, 0x96a406, 0x3, 0x40000a0048, 0xd, 0x0, 0x97d58d, 0x5, ...)
        /usr/local/go/src/net/hook.go:23 +0x58
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:293 +0x9c
internal/singleflight.(*Group).doCall(0xc64e30, 0x40000b2050, 0x40000a0060, 0x11, 0x4000090100)
        /usr/local/go/src/internal/singleflight/singleflight.go:95 +0x28
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:88 +0x30c

goroutine 22 [syscall]:
net._C2func_getaddrinfo(0x400009e130, 0x0, 0x4000096600, 0x40000b0038, 0x0, 0x0, 0x0)
        /tmp/go-build2748417885/b090/_cgo_gotypes.go:91 +0x48 fp=0x400013fd90 sp=0x400013fd60 pc=0x5709f8
net.cgoLookupIPCNAME.func1(0x400009e130, 0xe, 0xe, 0x4000096600, 0x40000b0038, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:161 +0xb0 fp=0x400013fde0 sp=0x400013fd90 pc=0x574580
net.cgoLookupIPCNAME(0x96a406, 0x3, 0x40000a0048, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/cgo_unix.go:161 +0x118 fp=0x400013ff10 sp=0x400013fde0 pc=0x571738
net.cgoIPLookup(0x4000092540, 0x96a406, 0x3, 0x40000a0048, 0xd)
        /usr/local/go/src/net/cgo_unix.go:218 +0x40 fp=0x400013ffb0 sp=0x400013ff10 pc=0x571cf0
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:228 +0x98
[signal SIGSEGV: segmentation violation code=0x1 addr=0x62 pc=0xffff84dbabf8]

runtime stack:
runtime.throw(0x97c280, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x54
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x29c

**Comment by StormYudi** [comment]
same problem here

**Comment by jacek900** [comment]
Same problem here. Raspberry Pi 4.

**Comment by vc5** [comment]
try this 
```
docker run --name miner \
   -v /path/to/plots:/plots/
   -v /path/to/config.yaml:/opt/config.yaml
   vincent5/hpool-chia-miner
```

**Comment by ferdiina** [comment]
Same problem here. Raspberry Pi 4.

**Comment by vespassassina** [comment]
same problem here. did someone tried ARM 32 ?

**Comment by almando** [comment]
Same problem here. Raspberry Pi 4.

**Comment by 0xBayMax** [comment]
Same problem here. Raspberry Pi 4.

**Comment by almando** [comment]
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x19df1ff0 pc=0xffff7ed44848]

runtime stack:
runtime.throw(0x97c280, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x54
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x29c

goroutine 1 [syscall]:
runtime.cgocall(0x709208, 0x400015b618, 0x4000134140)
	/usr/local/go/src/runtime/cgocall.go:154 +0x50 fp=0x400015b5e0 sp=0x400015b5a0 pc=0x403d60
os/user._Cfunc_mygetpwuid_r(0x3e8, 0x40001ae990, 0x19f061a0, 0x400, 0x4000134140, 0x200000000)
	/tmp/go-build2748417885/b104/_cgo_gotypes.go:172 +0x44 fp=0x400015b610 sp=0x400015b5e0 pc=0x6815a4
os/user.lookupUnixUid.func1.1(0x3e8, 0x40001ae990, 0x4000111b80, 0x4000134140, 0x400015b6c8)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0xc4 fp=0x400015b670 sp=0x400015b610 pc=0x682184
os/user.lookupUnixUid.func1(0x19f06101)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0x40 fp=0x400015b6b0 sp=0x400015b670 pc=0x6821f0
os/user.retryWithBuffer(0x4000111b80, 0x400015b7a0, 0x400015b778, 0x4cbf88)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x38 fp=0x400015b710 sp=0x400015b6b0 pc=0x681f38
os/user.lookupUnixUid(0x3e8, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0xcc fp=0x400015b7e0 sp=0x400015b710 pc=0x68194c
os/user.current(0x400015b8d8, 0x4513a8, 0x400015b848)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:49 +0x3c fp=0x400015b820 sp=0x400015b7e0 pc=0x68184c
os/user.Current.func1()
	/usr/local/go/src/os/user/lookup.go:15 +0x20 fp=0x400015b850 sp=0x400015b820 pc=0x682030
sync.(*Once).doSlow(0xc651e0, 0x989fd0)
	/usr/local/go/src/sync/once.go:68 +0x11c fp=0x400015b8b0 sp=0x400015b850 pc=0x47feec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
os/user.Current(0xc22aa0, 0x95aba0, 0x4000115790)
	/usr/local/go/src/os/user/lookup.go:15 +0xfc fp=0x400015b8e0 sp=0x400015b8b0 pc=0x68142c
github.com/trying2016/common-tools/utils.HomePath(0x4000115790, 0x4000132800, 0xa, 0x4000131410)
	vendor/github.com/trying2016/common-tools/utils/path.go:20 +0x20 fp=0x400015b910 sp=0x400015b8e0 pc=0x689d50
github.com/trying2016/common-tools/utils.GetHomePath(0x4000131410, 0xa, 0x400015b9f8, 0x1)
	vendor/github.com/trying2016/common-tools/utils/path.go:72 +0x20 fp=0x400015b970 sp=0x400015b910 pc=0x68a000
hpool.com/dev/miner-client/miner.(*Wrapper).readMinerId(0x400019a2d0)
	miner/wrapper_miner.go:185 +0xa0 fp=0x400015ba10 sp=0x400015b970 pc=0x6d9480
hpool.com/dev/miner-client/miner.(*Wrapper).Start(0x400019a2d0, 0x4000134008, 0x97ef5d)
	miner/wrapper_miner.go:88 +0x2ac fp=0x400015bbe0 sp=0x400015ba10 pc=0x6d8f1c
hpool.com/dev/miner-client/platform.Run(0x400015bf40, 0x40001002a0, 0x9f11f8, 0x400019a2d0)
	platform/console.go:54 +0x620 fp=0x400015bea0 sp=0x400015bbe0 pc=0x6dc8d0
main.main()
	main.go:109 +0x414 fp=0x400015bf70 sp=0x400015bea0 pc=0x708b84
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x274 fp=0x400015bfd0 sp=0x400015bf70 pc=0x437214
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x400015bfd0 sp=0x400015bfd0 pc=0x46ba54

goroutine 37 [select]:
net/http.(*Transport).getConn(0xc28ca0, 0x40002dc000, 0x0, 0x97d58d, 0x5, 0x40002bc048, 0x11, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1368 +0x418
net/http.(*Transport).roundTrip(0xc28ca0, 0x40002c0100, 0xf8, 0x95e040, 0x40001171b8)
	/usr/local/go/src/net/http/transport.go:579 +0x5c4
net/http.(*Transport).RoundTrip(0xc28ca0, 0x40002c0100, 0xc28ca0, 0xc0240dede75e350d, 0x6fcbf3c77)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x30
net/http.send(0x40002c0000, 0x9e69e8, 0xc28ca0, 0xc0240dede75e350d, 0x6fcbf3c77, 0xc657e0, 0x0, 0x40002cc008, 0x40002b2150, 0x1)
	/usr/local/go/src/net/http/client.go:251 +0x348
net/http.(*Client).send(0x40002b20f0, 0x40002c0000, 0xc0240dede75e350d, 0x6fcbf3c77, 0xc657e0, 0x40002cc008, 0x0, 0x1, 0x96d401)
	/usr/local/go/src/net/http/client.go:175 +0xc8
net/http.(*Client).do(0x40002b20f0, 0x40002c0000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:717 +0x33c
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:585
github.com/trying2016/common-tools/utils.(*HttpClient).do(0x4000117be8, 0x96a5cb, 0x4, 0x97d58d, 0x2e, 0x40002bc018, 0x18, 0x18, 0x40002ae8b8, 0x6d618c, ...)
	vendor/github.com/trying2016/common-tools/utils/httpClient.go:278 +0x2d8
github.com/trying2016/common-tools/utils.(*HttpClient).Post(0x4000117be8, 0x97d58d, 0x2e, 0x4, 0x40002b4098, 0x0, 0x0, 0x0)
	vendor/github.com/trying2016/common-tools/utils/httpClient.go:140 +0xa8
hpool.com/dev/miner-client/miner.(*Wrapper).CheckVersion(0x400019a2d0, 0x400013dd18, 0x0, 0x0, 0x0, 0x0)
	miner/api.go:56 +0x160
hpool.com/dev/miner-client/miner.(*Wrapper).checkVersion(0x400019a2d0)
	miner/wrapper_miner.go:47 +0x70
hpool.com/dev/miner-client/miner.(*Wrapper).Start.func1()
	miner/wrapper_miner.go:71 +0x28
github.com/trying2016/common-tools/utils.SafeGo.func1(0x0, 0x4000111b10)
	vendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x50
created by github.com/trying2016/common-tools/utils.SafeGo
	vendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x44

goroutine 38 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0x40001ae930)
	vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0x84
created by github.com/trying2016/common-tools/utils.(*Queue).init
	vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x124

goroutine 39 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0x4000111b30, 0x4000134130)
	vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x8c
created by github.com/trying2016/common-tools/utils.StartTime
	vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x90

goroutine 40 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0x40001ae960)
	vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0x84
created by github.com/trying2016/common-tools/utils.(*Queue).init
	vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x124

goroutine 41 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/go/src/runtime/time.go:193 +0xcc
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).run(0x4000149880)
	miner/chain/chia/prove.go:159 +0x10c
github.com/trying2016/common-tools/utils.SafeGo.func1(0x9898e8, 0x4000111b50)
	vendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x50
created by github.com/trying2016/common-tools/utils.SafeGo
	vendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x44

goroutine 42 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x927c0, 0x4000111b60, 0x4000134138)
	vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x8c
created by github.com/trying2016/common-tools/utils.StartTime
	vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x90

goroutine 50 [select]:
net.(*Resolver).lookupIPAddr(0xc64e20, 0x9ece08, 0x40002ce000, 0x96a406, 0x3, 0x40002bc048, 0xd, 0x1bb, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup.go:299 +0x504
net.(*Resolver).internetAddrList(0xc64e20, 0x9ece08, 0x40002ce000, 0x96a406, 0x3, 0x40002bc048, 0x11, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:280 +0x428
net.(*Resolver).resolveAddrList(0xc64e20, 0x9ece08, 0x40002ce000, 0x96a683, 0x4, 0x96a406, 0x3, 0x40002bc048, 0x11, 0x0, ...)
	/usr/local/go/src/net/dial.go:221 +0x3d4
net.(*Dialer).DialContext(0x4000136300, 0x9ece08, 0x40002ce000, 0x96a406, 0x3, 0x40002bc048, 0x11, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:403 +0x180
net/http.(*Transport).dial(0xc28ca0, 0x9ece08, 0x40002ce000, 0x96a406, 0x3, 0x40002bc048, 0x11, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1162 +0x178
net/http.(*Transport).dialConn(0xc28ca0, 0x9ece08, 0x40002ce000, 0x0, 0x97d58d, 0x5, 0x40002bc048, 0x11, 0x0, 0x40002b46c0, ...)
	/usr/local/go/src/net/http/transport.go:1600 +0x155c
net/http.(*Transport).dialConnFor(0xc28ca0, 0x40002e0000)
	/usr/local/go/src/net/http/transport.go:1442 +0x90
created by net/http.(*Transport).queueForDial
	/usr/local/go/src/net/http/transport.go:1411 +0x3a8

goroutine 51 [select]:
net.cgoLookupIP(0x9ecd98, 0x40002dc080, 0x96a406, 0x3, 0x40002bc048, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:229 +0x104
net.(*Resolver).lookupIP(0xc64e20, 0x9ecd98, 0x40002dc080, 0x96a406, 0x3, 0x40002bc048, 0xd, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup_unix.go:96 +0x114
net.glob..func1(0x9ecd98, 0x40002dc080, 0x40002b6100, 0x96a406, 0x3, 0x40002bc048, 0xd, 0x0, 0x97d58d, 0x5, ...)
	/usr/local/go/src/net/hook.go:23 +0x58
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:293 +0x9c
internal/singleflight.(*Group).doCall(0xc64e30, 0x40002d0050, 0x40002bc060, 0x11, 0x40002dc0c0)
	/usr/local/go/src/internal/singleflight/singleflight.go:95 +0x28
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:88 +0x30c

goroutine 52 [syscall]:
net._C2func_getaddrinfo(0x40002ba130, 0x0, 0x40002b2600, 0x40002cc038, 0x0, 0x0, 0x0)
	/tmp/go-build2748417885/b090/_cgo_gotypes.go:91 +0x48 fp=0x400013dd90 sp=0x400013dd60 pc=0x5709f8
net.cgoLookupIPCNAME.func1(0x40002ba130, 0xe, 0xe, 0x40002b2600, 0x40002cc038, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:161 +0xb0 fp=0x400013dde0 sp=0x400013dd90 pc=0x574580
net.cgoLookupIPCNAME(0x96a406, 0x3, 0x40002bc048, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:161 +0x118 fp=0x400013df10 sp=0x400013dde0 pc=0x571738
net.cgoIPLookup(0x40002ce4e0, 0x96a406, 0x3, 0x40002bc048, 0xd)
	/usr/local/go/src/net/cgo_unix.go:218 +0x40 fp=0x400013dfb0 sp=0x400013df10 pc=0x571cf0
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:228 +0x98
[signal SIGSEGV: segmentation violation code=0x1 addr=0x62 pc=0xffff7ee3ebf8]

runtime stack:
runtime.throw(0x97c280, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x54
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x29c

**Comment by Handola** [comment]
Same problem here. Raspberry Pi 4.

**Comment by MRTRALHA** [comment]
Same here. also tried ARM version only and does not work....  It gives connection timeput pr somthing. There is a ticket with that complaint already.

**Comment by rosystain** [comment]
Same here.

**Comment by corvin84** [comment]
Same here. Have been running 1.3.0.6 without any issues on PI4 - 8GB. I have nothing else on my machine but Hpool-miner and the new version does not work it throws a seg fault error. I have at least 6 GB memory free and the new client crashes. Please don't mandate the upgrade to 1.4.0.2 as it does not work.

**Comment by zl319** [comment]
![image](https://user-images.githubusercontent.com/85951548/122091368-4d49b300-ce3b-11eb-9d8c-ce7880e03264.png)


Operating environment：
Quad core arm cortex-a55 processor @ 1.9 GHz
4GB DDR3 / 64GB eMMC
Debian GNU/Linux 10 (buster) with Linux 5.4.108

HPool-Miner-chia-v1.4.1-0-arm、HPool-Miner-chia-v1.4.1-0-aarch64 cannot execute

Unable to run, important error

seek help
seek help
seek help
seek help
