### ISSUE TITLE
Raspberry pi running error

### ISSUE THREAD

**Issue by islamsahin** [hpool-dev/chia-miner#508]
ı execute Hpool miner v1.4.0-2-linux but dont execute..

 OS : Raspian OS 

ı dont execute arm version. How's arm versiın running ? Link or video.

Thanks.

error desc : 
unexpected fault address 0xe58d308c
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe58d308c pc=0x62357d]

goroutine 30 [running]:
runtime.throw(0x9ad76c, 0x5)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0x900426b0 sp=0x9004268                                                                                                                                                             0 pc=0x43eb92
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:741 +0x268 fp=0x900426e8 sp=0x9                                                                                                                                                             00426b0 pc=0x4562e8
vendor/golang.org/x/crypto/curve25519.ladderstep(0x90042848)
        /usr/local/go/src/vendor/golang.org/x/crypto/curve25519/curve25519_amd64                                                                                                                                                             .s:101 +0x5d fp=0x90042820 sp=0x900426e8 pc=0x62357d
vendor/golang.org/x/crypto/curve25519.mladder(0x90042980, 0x90042958, 0x90042938                                                                                                                                                             )
        /usr/local/go/src/vendor/golang.org/x/crypto/curve25519/curve25519_amd64                                                                                                                                                             .go:52 +0x136 fp=0x90042920 sp=0x90042820 pc=0x622956
vendor/golang.org/x/crypto/curve25519.scalarMult(0x900190a0, 0x90042a10, 0xe54f2                                                                                                                                                             0)
        /usr/local/go/src/vendor/golang.org/x/crypto/curve25519/curve25519_amd64                                                                                                                                                             .go:71 +0xe7 fp=0x900429b8 sp=0x90042920 pc=0x622ae7
vendor/golang.org/x/crypto/curve25519.ScalarMult(...)
        /usr/local/go/src/vendor/golang.org/x/crypto/curve25519/curve25519.go:21
vendor/golang.org/x/crypto/curve25519.ScalarBaseMult(...)
        /usr/local/go/src/vendor/golang.org/x/crypto/curve25519/curve25519.go:30
vendor/golang.org/x/crypto/curve25519.x25519(0x900190a0, 0x90019080, 0x20, 0x20,                                                                                                                                                              0xe54f20, 0x20, 0x20, 0x0, 0x0, 0x90042b30, ...)
        /usr/local/go/src/vendor/golang.org/x/crypto/curve25519/curve25519.go:85                                                                                                                                                              +0x22d fp=0x90042a80 sp=0x900429b8 pc=0x62266d
vendor/golang.org/x/crypto/curve25519.X25519(...)
        /usr/local/go/src/vendor/golang.org/x/crypto/curve25519/curve25519.go:71
crypto/tls.generateECDHEParameters(0xa29340, 0x900668d0, 0x1d, 0x0, 0x13, 0x900b                                                                                                                                                             8900, 0x10)
        /usr/local/go/src/crypto/tls/key_schedule.go:118 +0x153 fp=0x90042b40 sp                                                                                                                                                             =0x90042a80 pc=0x64ce53
crypto/tls.(*Conn).makeClientHello(0x900dc700, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/handshake_client.go:127 +0x828 fp=0x90042c5                                                                                                                                                             8 sp=0x90042b40 pc=0x634d28
crypto/tls.(*Conn).clientHandshake(0x900dc700, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/handshake_client.go:146 +0x7d fp=0x90042ee0                                                                                                                                                              sp=0x90042c58 pc=0x6354bd
crypto/tls.(*Conn).clientHandshake-fm(0x0, 0x0)
        /usr/local/go/src/crypto/tls/handshake_client.go:137 +0x33 fp=0x90042f08                                                                                                                                                              sp=0x90042ee0 pc=0x661513
crypto/tls.(*Conn).Handshake(0x900dc700, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1391 +0xc9 fp=0x90042f78 sp=0x90042                                                                                                                                                             f08 pc=0x633cc9
net/http.(*persistConn).addTLS.func2(0x0, 0x900dc700, 0x9005b220, 0x901eecc0)
        /usr/local/go/src/net/http/transport.go:1530 +0x45 fp=0x90042fc0 sp=0x90                                                                                                                                                             042f78 pc=0x6e99e5
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0x90042fc8 sp=0x90042                                                                                                                                                             fc0 pc=0x4783c1
created by net/http.(*persistConn).addTLS
        /usr/local/go/src/net/http/transport.go:1526 +0x1f6

goroutine 1 [select]:
net/http.(*persistConn).roundTrip(0x901e65a0, 0x90058c40, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:2610 +0x765
net/http.(*Transport).roundTrip(0xe4ec60, 0x90014d00, 0x9a0e40, 0x101, 0x90014d0                                                                                                                                                             0)
        /usr/local/go/src/net/http/transport.go:592 +0xacb
net/http.(*Transport).RoundTrip(0xe4ec60, 0x90014d00, 0xe4ec60, 0xc02424f90b9ba7                                                                                                                                                             8f, 0xe13f91ab0)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0x90014b00, 0xa29900, 0xe4ec60, 0xc02424f90b9ba78f, 0xe13f91ab0, 0                                                                                                                                                             xe8a260, 0x90010198, 0xc02424f90b9ba78f, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0x900e6de0, 0x90014b00, 0xc02424f90b9ba78f, 0xe13f91ab0,                                                                                                                                                              0xe8a260, 0x90010198, 0x0, 0x1, 0x900178c0)
        /usr/local/go/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0x900e6de0, 0x90014b00, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:585
github.com/trying2016/common-tools/utils.(*HttpClient).do(0x900a1818, 0x9ad017,                                                                                                                                                              0x3, 0x90076540, 0x2e, 0x0, 0x0, 0x0, 0x900a1520, 0x8bb95017, ...)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:278 +0x3c5
github.com/trying2016/common-tools/utils.(*HttpClient).Get(0x900a1818, 0x9007654                                                                                                                                                             0, 0x2e, 0x7, 0x901e6408, 0x9bfd57, 0x2d, 0x900b8880)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:155 +0xba
hpool.com/dev/miner-client/miner/server/line.(*Manager).update(0x900fa7e0)
        miner/server/line/manager.go:123 +0x2e6
hpool.com/dev/miner-client/miner/server/line.NewManager(0x9bc5a0, 0x24, 0x92c3c0                                                                                                                                                             )
        miner/server/line/manager.go:43 +0x206
hpool.com/dev/miner-client/miner/server.NewServer(0x9bc5a0, 0x24, 0x0)
        miner/server/server.go:18 +0x53
hpool.com/dev/miner-client/miner.(*Wrapper).Start(0x900ce2d0, 0x3, 0x0)
        miner/wrapper_miner.go:89 +0x33a
hpool.com/dev/miner-client/platform.Run(0x900a1f50, 0x9005c2a0, 0xa33ff8, 0x900c                                                                                                                                                             e2d0)
        platform/console.go:54 +0x6df
main.main()
        main.go:109 +0x44d

goroutine 8 [select]:
net/http.(*Transport).getConn(0xe4ec60, 0x90058cc0, 0x0, 0x9c03b3, 0x5, 0x9001a3                                                                                                                                                             d8, 0x11, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1368 +0x589
net/http.(*Transport).roundTrip(0xe4ec60, 0x90014a00, 0x9a0e40, 0x101, 0x90014a0                                                                                                                                                             0)
        /usr/local/go/src/net/http/transport.go:579 +0x7eb
net/http.(*Transport).RoundTrip(0xe4ec60, 0x90014a00, 0xe4ec60, 0xc02424f8e7418d                                                                                                                                                             5f, 0xdf4042ac8)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0x90014900, 0xa29900, 0xe4ec60, 0xc02424f8e7418d5f, 0xdf4042ac8, 0                                                                                                                                                             xe8a260, 0x90010178, 0xc02424f8e7418d5f, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0x900e6bd0, 0x90014900, 0xc02424f8e7418d5f, 0xdf4042ac8,                                                                                                                                                              0xe8a260, 0x90010178, 0x0, 0x1, 0x160)
        /usr/local/go/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0x900e6bd0, 0x90014900, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:585
github.com/trying2016/common-tools/utils.(*HttpClient).do(0x90085bf8, 0x9ad2f6,                                                                                                                                                              0x4, 0x9c03b3, 0x2e, 0x9001a378, 0x18, 0x18, 0x9437800e5fa99ee7, 0x10, ...)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:278 +0x3c5
github.com/trying2016/common-tools/utils.(*HttpClient).Post(0x90041bf8, 0x9c03b3                                                                                                                                                             , 0x2e, 0x4, 0x900d9dd8, 0x8, 0x10, 0x40904108)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:140 +0xc5
hpool.com/dev/miner-client/miner.(*Wrapper).CheckVersion(0x900ce2d0, 0x90030528,                                                                                                                                                              0x0, 0x900304d8, 0x41446d, 0x40904108)
        miner/api.go:56 +0x195
hpool.com/dev/miner-client/miner.(*Wrapper).checkVersion(0x900ce2d0)
        miner/wrapper_miner.go:47 +0xb0
hpool.com/dev/miner-client/miner.(*Wrapper).Start.func1()
        miner/wrapper_miner.go:71 +0x2a
github.com/trying2016/common-tools/utils.SafeGo.func1(0x0, 0x901dc2b0)
        vendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x4f
created by github.com/trying2016/common-tools/utils.SafeGo
        vendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x49

goroutine 9 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0x900e6a50)
        vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
        vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 10 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0x901dc2f0, 0x90                                                                                                                                                             010150)
        vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

goroutine 11 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0x900e6ab0)
        vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
        vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 12 [sleep]:
time.Sleep(0x5f5e100)
        /usr/local/go/src/runtime/time.go:193 +0xd2
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).run(0x9007f880)
        miner/chain/chia/prove.go:159 +0x147
github.com/trying2016/common-tools/utils.SafeGo.func1(0x9cc9c8, 0x901dc310)
        vendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x4f
created by github.com/trying2016/common-tools/utils.SafeGo
        vendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x49

goroutine 13 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x927c0, 0x901dc320, 0x                                                                                                                                                             90010158)
        vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

goroutine 14 [select]:
net/http.(*persistConn).roundTrip(0x901e67e0, 0x90058e00, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:2610 +0x765
net/http.(*Transport).roundTrip(0xe4ec60, 0x90015000, 0x9a0e40, 0x101, 0x9001500                                                                                                                                                             0)
        /usr/local/go/src/net/http/transport.go:592 +0xacb
net/http.(*Transport).RoundTrip(0xe4ec60, 0x90015000, 0xe4ec60, 0xc02424f9478845                                                                                                                                                             b2, 0xe4b807eeb)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0x90014f00, 0xa29900, 0xe4ec60, 0xc02424f9478845b2, 0xe4b807eeb, 0                                                                                                                                                             xe8a260, 0x900101e0, 0xc02424f9478845b2, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0x900e73b0, 0x90014f00, 0xc02424f9478845b2, 0xe4b807eeb,                                                                                                                                                              0xe8a260, 0x900101e0, 0x0, 0x1, 0x90017a59)
        /usr/local/go/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0x900e73b0, 0x90014f00, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:585
github.com/trying2016/common-tools/utils.(*HttpClient).do(0x901f9d98, 0x9ad017,                                                                                                                                                              0x3, 0x90076540, 0x2e, 0x0, 0x0, 0x0, 0x901f9aa0, 0xff8732ee, ...)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:278 +0x3c5
github.com/trying2016/common-tools/utils.(*HttpClient).Get(0x901f9d98, 0x9007654                                                                                                                                                             0, 0x2e, 0x7, 0x901e6768, 0x9bfd57, 0x2d, 0x900b88c0)
        vendor/github.com/trying2016/common-tools/utils/httpClient.go:155 +0xba
hpool.com/dev/miner-client/miner/server/line.(*Manager).update(0x900fa7e0)
        miner/server/line/manager.go:123 +0x2e6
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0x901dc3e0, 0x90                                                                                                                                                             010188)
        vendor/github.com/trying2016/common-tools/utils/timer.go:26 +0x30
created by github.com/trying2016/common-tools/utils.StartTime
        vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

goroutine 15 [chan receive]:
net/http.(*persistConn).addTLS(0x901e6480, 0x9001a3d8, 0xd, 0x0, 0x9001a3e6, 0x3                                                                                                                                                             )
        /usr/local/go/src/net/http/transport.go:1536 +0x21f
net/http.(*Transport).dialConn(0xe4ec60, 0xa2fc68, 0x9007b980, 0x0, 0x9c03b3, 0x                                                                                                                                                             5, 0x9001a3d8, 0x11, 0x0, 0x901e6480, ...)
        /usr/local/go/src/net/http/transport.go:1610 +0x1e05
net/http.(*Transport).dialConnFor(0xe4ec60, 0x900ac6e0)
        /usr/local/go/src/net/http/transport.go:1442 +0xc6
created by net/http.(*Transport).queueForDial
        /usr/local/go/src/net/http/transport.go:1411 +0x40f

goroutine 31 [runnable]:
internal/poll.runtime_pollWait(0x8ff83ce8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0x90099298, 0x72, 0x1000, 0x1000, 0xfffffffffffff                                                                                                                                                             fff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x90099280, 0x901fe000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0x90099280, 0x901fe000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0x90010218, 0x901fe000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0x901e67e0, 0x901fe000, 0x1000, 0x1000, 0x40c5f0, 0                                                                                                                                                             x60, 0x0)
        /usr/local/go/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0x901eed20)
        /usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0x901eed20, 0x1, 0x9005cf60, 0x9002ad98, 0x4150d8, 0x58, 0x                                                                                                                                                             998020)
        /usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0x901e67e0)
        /usr/local/go/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1743 +0xc77

goroutine 28 [runnable]:
internal/poll.runtime_pollWait(0x8ff83c00, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0x90099218, 0x72, 0x1000, 0x1000, 0xfffffffffffff                                                                                                                                                             fff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x90099200, 0x901fc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0x90099200, 0x901fc000, 0x1000, 0x1000, 0x0, 0x100000000, 0x12                                                                                                                                                             6e1b4)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0x90010210, 0x901fc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0x901e65a0, 0x901fc000, 0x1000, 0x1000, 0x40c5f0, 0                                                                                                                                                             x60, 0x0)
        /usr/local/go/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0x901eec60)
        /usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0x901eec60, 0x1, 0x9005ce40, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0x901e65a0)
        /usr/local/go/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1743 +0xc77

goroutine 32 [select]:
net/http.(*persistConn).writeLoop(0x901e67e0)
        /usr/local/go/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1744 +0xc9c

goroutine 29 [select]:
net/http.(*persistConn).writeLoop(0x901e65a0)
        /usr/local/go/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1744 +0xc9c

**Comment by fwt11** [comment]
same problem

**Comment by songshuailin** [comment]
same problem

**Comment by trying2016** [comment]
How big is your Raspberry Pi's memory? If the memory is not enough, there may be an abnormal crash

**Comment by Hexagonale** [comment]
Same error raspberry pi 4 with ubuntu server, 2GB RAM + 2GB SWAP (at the time of running 1.8GB RAM free). Definitely not memory error

**Comment by trying2016** [comment]
Load the directory to reduce the number of attempts. The current guess may be caused by insufficient memory

**Comment by adnkai** [comment]
> Load the directory to reduce the number of attempts. The current guess may be caused by insufficient memory

Can't confirm. 4Gb memory here. Same problem on Rpi4 with ubuntu server 20.04.

**Comment by Akaino** [comment]
> Load the directory to reduce the number of attempts. The current guess may be caused by insufficient memory

Can't confirm. 4Gb memory here. Same problem on Rpi4 with ubuntu server 20.04.

**Comment by sigi77777** [comment]
rasp. 4 with 8gb memory, same error!

**Comment by kozzar** [comment]
At this moment (and also in previous versions, where this problem exist) I solved it, forcing to execute the program, using endless loop:

```
while true
 do
  sudo ./hpool-chia-miner-linux-arm64
 done
```

I know it's "ugly" way, but after a few attempts (4-5), program finally starts.
Also if there is some error, which crash program (like fatal error: unexpected signal during runtime execution).

**Comment by adnkai** [comment]
> At this moment (and also in previous versions, where this problem exist) I solved it, forcing to execute the program, using endless loop:
> 
> ```
> while true
>  do
>   sudo ./hpool-chia-miner-linux-arm64
>  done
> ```
> 
> I know it's "ugly" way, but after a few attempts (4-5), program finally starts.
> Also if there is some error, which crash program (like fatal error: unexpected signal during runtime execution).

This is... Like the utmost worst advice i've ever read. Anywhere online.
Segmentation Fault Issues can't be tackled by just looping exuction until it finally (accidentally) executes.
There's so much wrong in this attempt...

**Comment by kozzar** [comment]
> > At this moment (and also in previous versions, where this problem exist) I solved it, forcing to execute the program, using endless loop:
> > ```
> > while true
> >  do
> >   sudo ./hpool-chia-miner-linux-arm64
> >  done
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I know it's "ugly" way, but after a few attempts (4-5), program finally starts.
> > Also if there is some error, which crash program (like fatal error: unexpected signal during runtime execution).
> 
> This is... Like the utmost worst advice i've ever read. Anywhere online.
> Segmentation Fault Issues can't be tackled by just looping exuction until it finally (accidentally) executes.
> There's so much wrong in this attempt...

Ok, I understand, but in this situation tell us advice, what is your solution in this case?
Because if not this method, I wouldn't farm.. So it's still better in this way, to have something, then nothing.
I have fresh raspberry pi 4 with 8gb, Raspbian GNU/Linux 10 (buster).
Version 1.3.0-1 was working very well.

**Comment by adnkai** [comment]
> Ok, I understand, but in this situation tell us advice, what is your solution in this case?
> Because if not this method, I wouldn't farm.. So it's still better in this way, to have something, then nothing.
> I have fresh raspberry pi 4 with 8gb, Raspbian GNU/Linux 10 (buster).
> Version 1.3.0-1 was working very well.

The solution should be a working version.
My solution is falling back to 1.3.0 until the problems are resolved. 
If they aren't resolved in time, another machine has to become hpool miner.

**Comment by Hexagonale** [comment]
Rollback is best solution for now. Previous version works just fine.

**Comment by zl319** [comment]
![image](https://user-images.githubusercontent.com/85951548/122091811-ca752800-ce3b-11eb-818d-683fb72b2f35.png)


Operating environment：
Quad core arm cortex-a55 processor @ 1.9 GHz
4GB DDR3 / 64GB eMMC
Debian GNU/Linux 10 (buster) with Linux 5.4.108

HPool-Miner-chia-v1.4.1-0-arm、HPool-Miner-chia-v1.4.1-0-aarch64 cannot execute

Unable to run, important error

seek help
seek help
seek help
seek help
