### ISSUE TITLE
ARM64 (AARCH64) Getting a panic and not working

### ISSUE THREAD

**Issue by N0Klu3** [hpool-dev/chia-miner#559]
Hey all, 
After all the issues with the ARM 32Bit version I re-installed my RPI with Ubuntu MATE 64bit and downloaded the AARCH64 build.

When running it I get: 
```
Rlimit Final {999999 999999}
***************************************************
**** Miner:HPool-Miner-Chia
**** Version:v1.4.0 2
**** BuildTime:2021-05-26-15:00:00 GMT
**** MinerName:chiafarmer
**** ApiKey:xxx
***************************************************
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34008f60 pc=0xffff802369c0]

runtime stack:
runtime.throw(0x97c280, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x54
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x29c

goroutine 1 [syscall]:
runtime.cgocall(0x709208, 0x400015b618, 0x4000134140)
	/usr/local/go/src/runtime/cgocall.go:154 +0x50 fp=0x400015b5e0 sp=0x400015b5a0 pc=0x403d60
os/user._Cfunc_mygetpwuid_r(0x3e8, 0x40001b8990, 0x3411d060, 0x400, 0x4000134140, 0x200000000)
	/tmp/go-build2748417885/b104/_cgo_gotypes.go:172 +0x44 fp=0x400015b610 sp=0x400015b5e0 pc=0x6815a4
os/user.lookupUnixUid.func1.1(0x3e8, 0x40001b8990, 0x4000111ba0, 0x4000134140, 0x400015b6c8)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0xc4 fp=0x400015b670 sp=0x400015b610 pc=0x682184
os/user.lookupUnixUid.func1(0x3411d001)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0x40 fp=0x400015b6b0 sp=0x400015b670 pc=0x6821f0
os/user.retryWithBuffer(0x4000111ba0, 0x400015b7a0, 0x400015b778, 0x4cbf88)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x38 fp=0x400015b710 sp=0x400015b6b0 pc=0x681f38
os/user.lookupUnixUid(0x3e8, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0xcc fp=0x400015b7e0 sp=0x400015b710 pc=0x68194c
os/user.current(0x400015b8d8, 0x4513a8, 0x400015b848)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:49 +0x3c fp=0x400015b820 sp=0x400015b7e0 pc=0x68184c
os/user.Current.func1()
	/usr/local/go/src/os/user/lookup.go:15 +0x20 fp=0x400015b850 sp=0x400015b820 pc=0x682030
sync.(*Once).doSlow(0xc651e0, 0x989fd0)
	/usr/local/go/src/sync/once.go:68 +0x11c fp=0x400015b8b0 sp=0x400015b850 pc=0x47feec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
os/user.Current(0xc22aa0, 0x95aba0, 0x4000115ad0)
	/usr/local/go/src/os/user/lookup.go:15 +0xfc fp=0x400015b8e0 sp=0x400015b8b0 pc=0x68142c
github.com/trying2016/common-tools/utils.HomePath(0x4000115ad0, 0x4000132800, 0xa, 0x4000131440)
	vendor/github.com/trying2016/common-tools/utils/path.go:20 +0x20 fp=0x400015b910 sp=0x400015b8e0 pc=0x689d50
github.com/trying2016/common-tools/utils.GetHomePath(0x4000131440, 0xa, 0x400015b9f8, 0x1)
	vendor/github.com/trying2016/common-tools/utils/path.go:72 +0x20 fp=0x400015b970 sp=0x400015b910 pc=0x68a000
hpool.com/dev/miner-client/miner.(*Wrapper).readMinerId(0x40001c4240)
	miner/wrapper_miner.go:185 +0xa0 fp=0x400015ba10 sp=0x400015b970 pc=0x6d9480
hpool.com/dev/miner-client/miner.(*Wrapper).Start(0x40001c4240, 0x4000134008, 0x97ef5d)
	miner/wrapper_miner.go:88 +0x2ac fp=0x400015bbe0 sp=0x400015ba10 pc=0x6d8f1c
hpool.com/dev/miner-client/platform.Run(0x400015bf40, 0x4000100360, 0x9f11f8, 0x40001c4240)
	platform/console.go:54 +0x620 fp=0x400015bea0 sp=0x400015bbe0 pc=0x6dc8d0
main.main()
	main.go:109 +0x414 fp=0x400015bf70 sp=0x400015bea0 pc=0x708b84
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x274 fp=0x400015bfd0 sp=0x400015bf70 pc=0x437214
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x400015bfd0 sp=0x400015bfd0 pc=0x46ba54

goroutine 37 [select]:
net/http.(*Transport).getConn(0xc28ca0, 0x400007c000, 0x0, 0x97d58d, 0x5, 0x400001a1c8, 0x11, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1368 +0x418
net/http.(*Transport).roundTrip(0xc28ca0, 0x400006c100, 0xf8, 0x95e040, 0x40001171b8)
	/usr/local/go/src/net/http/transport.go:579 +0x5c4
net/http.(*Transport).RoundTrip(0xc28ca0, 0x400006c100, 0xc28ca0, 0xc025f181938df07f, 0x6fccc985b)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x30
net/http.send(0x400006c000, 0x9e69e8, 0xc28ca0, 0xc025f181938df07f, 0x6fccc985b, 0xc657e0, 0x0, 0x4000010018, 0x4000066150, 0x1)
	/usr/local/go/src/net/http/client.go:251 +0x348
net/http.(*Client).send(0x40000660f0, 0x400006c000, 0xc025f181938df07f, 0x6fccc985b, 0xc657e0, 0x4000010018, 0x0, 0x1, 0x96d401)
	/usr/local/go/src/net/http/client.go:175 +0xc8
net/http.(*Client).do(0x40000660f0, 0x400006c000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:717 +0x33c
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:585
github.com/trying2016/common-tools/utils.(*HttpClient).do(0x4000117be8, 0x96a5cb, 0x4, 0x97d58d, 0x2e, 0x400001a198, 0x18, 0x18, 0x400004a8b8, 0x6d618c, ...)
	vendor/github.com/trying2016/common-tools/utils/httpClient.go:278 +0x2d8
github.com/trying2016/common-tools/utils.(*HttpClient).Post(0x4000117be8, 0x97d58d, 0x2e, 0x4, 0x400000c1b8, 0x0, 0x0, 0x0)
	vendor/github.com/trying2016/common-tools/utils/httpClient.go:140 +0xa8
hpool.com/dev/miner-client/miner.(*Wrapper).CheckVersion(0x40001c4240, 0x400013dd18, 0x0, 0x0, 0x0, 0x0)
	miner/api.go:56 +0x160
hpool.com/dev/miner-client/miner.(*Wrapper).checkVersion(0x40001c4240)
	miner/wrapper_miner.go:47 +0x70
hpool.com/dev/miner-client/miner.(*Wrapper).Start.func1()
	miner/wrapper_miner.go:71 +0x28
github.com/trying2016/common-tools/utils.SafeGo.func1(0x0, 0x4000111b30)
	vendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x50
created by github.com/trying2016/common-tools/utils.SafeGo
	vendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x44

goroutine 38 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0x40001b8930)
	vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0x84
created by github.com/trying2016/common-tools/utils.(*Queue).init
	vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x124

goroutine 39 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0x4000111b50, 0x4000134130)
	vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x8c
created by github.com/trying2016/common-tools/utils.StartTime
	vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x90

goroutine 40 [select]:
github.com/trying2016/common-tools/utils.(*Queue).run(0x40001b8960)
	vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0x84
created by github.com/trying2016/common-tools/utils.(*Queue).init
	vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x124

goroutine 41 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/go/src/runtime/time.go:193 +0xcc
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).run(0x4000149880)
	miner/chain/chia/prove.go:159 +0x10c
github.com/trying2016/common-tools/utils.SafeGo.func1(0x9898e8, 0x4000111b70)
	vendor/github.com/trying2016/common-tools/utils/utils.go:182 +0x50
created by github.com/trying2016/common-tools/utils.SafeGo
	vendor/github.com/trying2016/common-tools/utils/utils.go:165 +0x44

goroutine 42 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x927c0, 0x4000111b80, 0x4000134138)
	vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x8c
created by github.com/trying2016/common-tools/utils.StartTime
	vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x90

goroutine 3 [select]:
net.(*Resolver).lookupIPAddr(0xc64e20, 0x9ece08, 0x4000064060, 0x96a406, 0x3, 0x400001a1c8, 0xd, 0x1bb, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup.go:299 +0x504
net.(*Resolver).internetAddrList(0xc64e20, 0x9ece08, 0x4000064060, 0x96a406, 0x3, 0x400001a1c8, 0x11, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:280 +0x428
net.(*Resolver).resolveAddrList(0xc64e20, 0x9ece08, 0x4000064060, 0x96a683, 0x4, 0x96a406, 0x3, 0x400001a1c8, 0x11, 0x0, ...)
	/usr/local/go/src/net/dial.go:221 +0x3d4
net.(*Dialer).DialContext(0x4000136300, 0x9ece08, 0x4000064060, 0x96a406, 0x3, 0x400001a1c8, 0x11, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:403 +0x180
net/http.(*Transport).dial(0xc28ca0, 0x9ece08, 0x4000064060, 0x96a406, 0x3, 0x400001a1c8, 0x11, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1162 +0x178
net/http.(*Transport).dialConn(0xc28ca0, 0x9ece08, 0x4000064060, 0x0, 0x97d58d, 0x5, 0x400001a1c8, 0x11, 0x0, 0x400000c7e0, ...)
	/usr/local/go/src/net/http/transport.go:1600 +0x155c
net/http.(*Transport).dialConnFor(0xc28ca0, 0x40002b2000)
	/usr/local/go/src/net/http/transport.go:1442 +0x90
created by net/http.(*Transport).queueForDial
	/usr/local/go/src/net/http/transport.go:1411 +0x3a8

goroutine 4 [select]:
net.cgoLookupIP(0x9ecd98, 0x400007c080, 0x96a406, 0x3, 0x400001a1c8, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:229 +0x104
net.(*Resolver).lookupIP(0xc64e20, 0x9ecd98, 0x400007c080, 0x96a406, 0x3, 0x400001a1c8, 0xd, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup_unix.go:96 +0x114
net.glob..func1(0x9ecd98, 0x400007c080, 0x4000012120, 0x96a406, 0x3, 0x400001a1c8, 0xd, 0x0, 0x97d58d, 0x5, ...)
	/usr/local/go/src/net/hook.go:23 +0x58
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:293 +0x9c
internal/singleflight.(*Group).doCall(0xc64e30, 0x4000078050, 0x400001a1e0, 0x11, 0x400007c0c0)
	/usr/local/go/src/internal/singleflight/singleflight.go:95 +0x28
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:88 +0x30c

goroutine 5 [syscall]:
net._C2func_getaddrinfo(0x4000016210, 0x0, 0x4000066660, 0x4000010048, 0x0, 0x0, 0x0)
	/tmp/go-build2748417885/b090/_cgo_gotypes.go:91 +0x48 fp=0x400013dd90 sp=0x400013dd60 pc=0x5709f8
net.cgoLookupIPCNAME.func1(0x4000016210, 0xe, 0xe, 0x4000066660, 0x4000010048, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:161 +0xb0 fp=0x400013dde0 sp=0x400013dd90 pc=0x574580
net.cgoLookupIPCNAME(0x96a406, 0x3, 0x400001a1c8, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:161 +0x118 fp=0x400013df10 sp=0x400013dde0 pc=0x571738
net.cgoIPLookup(0x4000064540, 0x96a406, 0x3, 0x400001a1c8, 0xd)
	/usr/local/go/src/net/cgo_unix.go:218 +0x40 fp=0x400013dfb0 sp=0x400013df10 pc=0x571cf0
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:228 +0x98
[signal SIGSEGV: segmentation violation code=0x1 addr=0x62 pc=0xffff802b42ec]

runtime stack:
runtime.throw(0x97c280, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x54
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x29c
```

This is a clean build of 20.10 Ubuntu MATE.
Am I missing something somewhere?

I changed the API key, it is the correct one when actually running it

**Comment by matheust3** [comment]
Same problem rir!

**Comment by kamil234** [comment]
You went as far as reimaging your RPi, why not just use version that's confirmed working?
Download Raspbian OS Lite
https://www.raspberrypi.org/software/operating-systems/
Mount it on a USB

Enable SSH
Mount disks
do full upgrade "sudo apt update && sudo apt full-upgrade"
Download miner "wget https://github.com/hpool-dev/chia-miner/releases/download/v1.4.0-2/HPool-Miner-chia-v1.4.0-2-arm.zip"
Extract & configure miner

Up and running in 20 minutes...

**Comment by N0Klu3** [comment]
> You went as far as reimaging your RPi, why not just use version that's confirmed working?
> Download Raspbian OS Lite
> https://www.raspberrypi.org/software/operating-systems/
> Mount it on a USB
> 
> Enable SSH
> Mount disks
> do full upgrade "sudo apt update && sudo apt full-upgrade"
> Download miner "wget https://github.com/hpool-dev/chia-miner/releases/download/v1.4.0-2/HPool-Miner-chia-v1.4.0-2-arm.zip"
> Extract & configure miner
> 
> Up and running in 20 minutes...

I can confirm the above works and this is what I ended up doing.
But still should be fixed.

**Comment by tiends** [comment]
```
cd /root/linux-arm64.1.4.0-2

docker run -it --rm \
--mount type=bind,source=/mnt,target=/mnt \
-v `pwd`:/app \
-w /app ubuntu:18.04 ./hpool-chia-miner-linux-arm64
```

**Comment by xiahongze** [comment]
Unfortunately I could not get docker to work on my NAS either. It kind of sucks.

**Comment by sergiors** [comment]
I got the same problem with RPI4 using ubuntu x64

**Comment by emcifuntik** [comment]
same on ubuntu x64

**Comment by sergiors** [comment]
@trying2016 did you see that?

**Comment by almando** [comment]
i have the same problem.

**Comment by hselomein** [comment]
I have this same issue as well. I am not using the RPi 64 but a QNAP TS-932PX nas that is using an arm64 cpu

**Comment by zl319** [comment]
![image](https://user-images.githubusercontent.com/85951548/122087080-ed510d80-ce36-11eb-974a-01df6bb583da.png)

Operating environment：
Quad core arm cortex-a55 processor @ 1.9 GHz
4GB DDR3 / 64GB eMMC
Debian GNU/Linux 10 (buster) with Linux 5.4.108

HPool-Miner-chia-v1.4.1-0-arm、HPool-Miner-chia-v1.4.1-0-aarch64     cannot execute

Unable to run, important error

seek help
seek help
seek help
seek help

**Comment by archerallstars** [comment]
Please note that as of the miner version 1.4.1, the **arm64** build (aarch64) **is not working**. We need to run the arm build (arm32) inside a docker using arm32v7/Ubuntu image to make it work.

1. Install docker:
`sudo apt install docker.io`

2. Pull the docker image (arm32):
`sudo docker pull arm32v7/ubuntu`

3. Create a docker script, for example, **hpool_docker.sh**. Inside the script, please use this code to bind your local directories to the docker:
```
docker run -it \
--mount type=bind,source=/media/user/D1,target=/media/user/D1 \
--mount type=bind,source=/media/user/D2,target=/media/user/D2 \
--mount type=bind,source=/media/user/D3,target=/media/user/D3 \
--mount type=bind,source=/home/user/Downloads/hpool,target=/home/user/Downloads/hpool \
arm32v7/ubuntu
```

4. Run the above script:
`sudo sh hpool_docker.sh`

5. `cd` to the miner's folder. It's `/home/user/Downloads/hpool` from the above script. Then, run the miner by `./miner`.

Please note that:
- The source and target path must correspond to the path in your setup.
- You can mount as many volumes (paths) as much as you want inside a docker, then you can specify the path to your plots in the miner's conf file.

**Comment by guacuco** [comment]
> > You went as far as reimaging your RPi, why not just use version that's confirmed working?
> > Download Raspbian OS Lite
> > https://www.raspberrypi.org/software/operating-systems/
> > Mount it on a USB
> > Enable SSH
> > Mount disks
> > do full upgrade "sudo apt update && sudo apt full-upgrade"
> > Download miner "wget https://github.com/hpool-dev/chia-miner/releases/download/v1.4.0-2/HPool-Miner-chia-v1.4.0-2-arm.zip"
> > Extract & configure miner
> > Up and running in 20 minutes...
> 
> I can confirm the above works and this is what I ended up doing.
> But still should be fixed.

But you know:  working fine !!!! Well done...

**Comment by wuzhefang** [comment]
> I have this same issue as well. I am not using the RPi 64 but a QNAP TS-932PX nas that is using an arm64 cpu

same here
