### ISSUE TITLE
Chiaminer v1.5.3 1 linux version shutdown each 30 minutes

### ISSUE THREAD

**Issue by wareck** [hpool-dev/chia-miner#695]
Hello
On my server (ubuntu 20), chiaminer stop working each 30 minutes for no reason.
I'm waiting for a new log and share this .

**Comment by wareck** [comment]
there is nothing abnormal in logfile...
the program just close

**Comment by wareck** [comment]
When crash I have this kind of message :
exception : Invalid size for deltas: 5382
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8c13df]

runtime stack:
runtime.throw(0x99d308, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 804 [syscall]:
runtime.cgocall(0x7a4490, 0xc00014ba68, 0x100)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00014ba38 sp=0xc00014ba00 pc=0x40705b
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos._Cfunc_GetFullProof(0x2f54d80, 0xc0004dcb80, 0x0, 0xc000097300, 0xffffffff, 0x0)
	/var/folders/ky/59p7y1xs3cd6q34r37zlv0gc0000gn/T/go-build2586713722/b146/_cgo_gotypes.go:98 +0x48 fp=0xc00014ba68 sp=0xc00014ba38 pc=0x72a8a8
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.GetFullProof.func1(0x2f54d80, 0xc0004dcb80, 0x20, 0x20, 0x0, 0xc000097300, 0x100, 0x100, 0xffffffffffffffff, 0x240)
	miner/chain/chia/common/chiapos/chia_static.go:76 +0x9c fp=0xc00014bab0 sp=0xc00014ba68 pc=0x72e11c
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.GetFullProof(0x2f54d80, 0xc0004dcb80, 0x20, 0x20, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0)
	miner/chain/chia/common/chiapos/chia_static.go:76 +0xc5 fp=0xc00014bb20 sp=0xc00014bab0 pc=0x72d985
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.(*File).GetFullProof(0xc0001306c0, 0xc0004dcb80, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffff00)
	miner/chain/chia/common/chiapos/chia.go:322 +0xc5 fp=0xc00014bb98 sp=0xc00014bb20 pc=0x72c385
hpool.com/dev/miner-client/miner/chain/chia.(*Prove).submitProve.func2()
	miner/chain/chia/prove.go:203 +0x7b fp=0xc00014bfb0 sp=0xc00014bb98 pc=0x745afb
github.com/trying2016/common-tools/utils.RunTimeout.func1(0xc0004cdea8, 0xc0003ce754)
	vendor/github.com/trying2016/common-tools/utils/utils.go:194 +0x27 fp=0xc00014bfd0 sp=0xc00014bfb0 pc=0x6fc2a7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00014bfd8 sp=0xc00014bfd0 pc=0x474ca1
created by github.com/trying2016/common-tools/utils.RunTimeout
	vendor/github.com/trying2016/common-tools/utils/utils.go:193 +0xa5

**Comment by room101-dev** [comment]
Seeing same problem, linux mint 19, odd that machines not running clones are not having this problem
I wonder if this really does have something to do with 'go-lang'
Would be easy to fix this memory leak ourselves if we had the source
Too bad that 'chia' only has one functional OG pool, this is what happens when you have closed source and only one pool.

The dev's seem to only care about the windows version, and give little to nothing of care about the linux version, this memory leak probably has actually been ongoing ever since they added this mass crap to the chia, why they did this is insane.

**Comment by anignatev** [comment]
We have seen the same issue!

Version: HPool-Miner-chia-og-v1.5.6-1, running on Linux CentOS 7.

Please, fix it or publish the source code!!

_________________________________________________________________________ 
Loading plotter files /mnt/data1/ (24/71) 33%
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8e1506]

runtime stack:
runtime.throw(0x9bc50e, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 10 [syscall]:
runtime.cgocall(0x7c09d0, 0xc0000a9190, 0xc0000a9100)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0000a9160 sp=0xc0000a9128 pc=0x40719b
hpool.com/dev/pool-wallet/pkg/crypto/bls._Cfunc_key_derive_child(0x131f7a0, 0xc00000305d, 0x0)
        /var/folders/ky/59p7y1xs3cd6q34r37zlv0gc0000gn/T/go-build1088925942/b158/_cgo_gotypes.go:202 +0x49 fp=0xc0000a9190 sp=0xc0000a9160 pc=0x73e569
hpool.com/dev/pool-wallet/pkg/crypto/bls.(*PrivateKey).DeriveChild.func1(0xc0000a9208, 0xc0000a9200, 0x131f7a0)
        vendor/hpool.com/dev/pool-wallet/pkg/crypto/bls/bls_cgo.go:112 +0x74 fp=0xc0000a91d0 sp=0xc0000a9190 pc=0x73f374
hpool.com/dev/pool-wallet/pkg/crypto/bls.(*PrivateKey).DeriveChild(0xc000510288, 0xc0000a92c8, 0x4, 0x4, 0x0)
        vendor/hpool.com/dev/pool-wallet/pkg/crypto/bls/bls_cgo.go:112 +0xb3 fp=0xc0000a9250 sp=0xc0000a91d0 pc=0x73ea13
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.(*File).CheckPlotId(0xc0003502d0, 0xc000131700)
        miner/chain/chia/common/chiapos/chia.go:513 +0x16f fp=0xc0000a9340 sp=0xc0000a9250 pc=0x74304f
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos._Open(0xc000308a80, 0x6a, 0x0, 0xc0000a9530, 0x16)
        miner/chain/chia/common/chiapos/chia.go:121 +0x225 fp=0xc0000a94e8 sp=0xc0000a9340 pc=0x7412a5
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.Open(0xc000308a80, 0x6a, 0x0, 0x0, 0x0)
        miner/chain/chia/common/chiapos/chia.go:158 +0x85 fp=0xc0000a9540 sp=0xc0000a94e8 pc=0x741725
hpool.com/dev/miner-client/miner/chain/chia.(*PlotterSpace).Load(0xc000482100, 0xc000133140, 0xb, 0x1)
        miner/chain/chia/plotterSpace.go:209 +0x3e6 fp=0xc0000a9fc0 sp=0xc0000a9540 pc=0x7532c6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000a9fc8 sp=0xc0000a9fc0 pc=0x474f01
created by hpool.com/dev/miner-client/miner/chain/chia.NewPlotterSpace
        miner/chain/chia/plotterSpace.go:68 +0x2fb

goroutine 1 [chan receive]:
hpool.com/dev/miner-client/platform.Run(0xc000163f50, 0xc000100240, 0xa37998, 0xc0001b6240)
        platform/console.go:84 +0x8f3
