### ISSUE TITLE
exception : Src size is incorrect

### ISSUE THREAD

**Issue by DavidJ68** [hpool-dev/chia-miner#698]
Hi everyone, I have below error message, can anyone help to fix, I'm running ubuntu. thanks

exception : Src size is incorrect
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8c13df]

runtime stack:
runtime.throw(0x99d308, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 5906 [syscall]:
runtime.cgocall(0x7a4490, 0xc000729a68, 0x100)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc000729a38 sp=0xc000729a00 pc=0x40705b
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos._Cfunc_GetFullProof(0x1aa0e40, 0xc001071ac0, 0x0, 0xc0005b0800, 0xffffffff, 0x0)

**Comment by room101-dev** [comment]
This is also post below under 'crash', this memory-leak has been happening randomly ever since they merged the mass with chia, in the past they didn't force us to run the new version, if there was a bug we could fall back, now must must run this new version which crashes every few hours.

Ok, time to setup a bash loop that just keeps running forever, its damn clear that  the morons who run HPOOL don't have a plan to fix this bug, and the fact that they forced us 3 days ago to use this new shit-version shows that they are trying to herd all the cats into PP, no other explanation for gross incompetence.

bash on line
#
begin:
./hpool-miner-chia           # run miner
delay 5                            # wait 5 seconds
goto begin                       # rinse & repeat forever

no other work around at this, now it just dies every hour and then you get an email from hpool that says you miner is down

They clearly have no intention of fix this memory leak, given its now almost a month old.

**Comment by trying2016** [comment]
Recommended download: https://github.com/hpool-dev/chia-miner/releases/tag/1.5.3
The new version fixes the software crash problem

**Comment by anignatev** [comment]
We have seen the same issue!

Version: HPool-Miner-chia-og-v1.5.6-1, running on Linux CentOS 7.

Please, fix it or publish the source code!!

_________________________________________________________________________ 
Loading plotter files /mnt/data1/ (24/71) 33%
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8e1506]

runtime stack:
runtime.throw(0x9bc50e, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 10 [syscall]:
runtime.cgocall(0x7c09d0, 0xc0000a9190, 0xc0000a9100)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0000a9160 sp=0xc0000a9128 pc=0x40719b
hpool.com/dev/pool-wallet/pkg/crypto/bls._Cfunc_key_derive_child(0x131f7a0, 0xc00000305d, 0x0)
        /var/folders/ky/59p7y1xs3cd6q34r37zlv0gc0000gn/T/go-build1088925942/b158/_cgo_gotypes.go:202 +0x49 fp=0xc0000a9190 sp=0xc0000a9160 pc=0x73e569
hpool.com/dev/pool-wallet/pkg/crypto/bls.(*PrivateKey).DeriveChild.func1(0xc0000a9208, 0xc0000a9200, 0x131f7a0)
        vendor/hpool.com/dev/pool-wallet/pkg/crypto/bls/bls_cgo.go:112 +0x74 fp=0xc0000a91d0 sp=0xc0000a9190 pc=0x73f374
hpool.com/dev/pool-wallet/pkg/crypto/bls.(*PrivateKey).DeriveChild(0xc000510288, 0xc0000a92c8, 0x4, 0x4, 0x0)
        vendor/hpool.com/dev/pool-wallet/pkg/crypto/bls/bls_cgo.go:112 +0xb3 fp=0xc0000a9250 sp=0xc0000a91d0 pc=0x73ea13
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.(*File).CheckPlotId(0xc0003502d0, 0xc000131700)
        miner/chain/chia/common/chiapos/chia.go:513 +0x16f fp=0xc0000a9340 sp=0xc0000a9250 pc=0x74304f
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos._Open(0xc000308a80, 0x6a, 0x0, 0xc0000a9530, 0x16)
        miner/chain/chia/common/chiapos/chia.go:121 +0x225 fp=0xc0000a94e8 sp=0xc0000a9340 pc=0x7412a5
hpool.com/dev/miner-client/miner/chain/chia/common/chiapos.Open(0xc000308a80, 0x6a, 0x0, 0x0, 0x0)
        miner/chain/chia/common/chiapos/chia.go:158 +0x85 fp=0xc0000a9540 sp=0xc0000a94e8 pc=0x741725
hpool.com/dev/miner-client/miner/chain/chia.(*PlotterSpace).Load(0xc000482100, 0xc000133140, 0xb, 0x1)
        miner/chain/chia/plotterSpace.go:209 +0x3e6 fp=0xc0000a9fc0 sp=0xc0000a9540 pc=0x7532c6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000a9fc8 sp=0xc0000a9fc0 pc=0x474f01
created by hpool.com/dev/miner-client/miner/chain/chia.NewPlotterSpace
        miner/chain/chia/plotterSpace.go:68 +0x2fb

goroutine 1 [chan receive]:
hpool.com/dev/miner-client/platform.Run(0xc000163f50, 0xc000100240, 0xa37998, 0xc0001b6240)
        platform/console.go:84 +0x8f3
