### ISSUE TITLE
linux 版算力经常崩溃

### ISSUE THREAD

**Issue by little-snow-fox** [hpool-dev/chia-miner#92]
希望你们能够解决这个不安全的线程操作
```
time="2021-05-04T02:26:33Z" level=info msg="new mining info" file=loggers.go func=logging.CPrint height=227321 jobId=2017566089 line=168 tid=7522
time="2021-05-04T02:26:45Z" level=info msg="new mining info" file=loggers.go func=logging.CPrint height=227321 jobId=886400692 line=168 tid=7522
time="2021-05-04T02:26:53Z" level=info msg="new mining info" file=loggers.go func=logging.CPrint height=227321 jobId=2645309846 line=168 tid=7522
time="2021-05-04T02:26:54Z" level=info msg="switch line" chain=CHIA file=loggers.go func=logging.CPrint line=168 tid=52 type=ws
time="2021-05-04T02:26:54Z" level=info msg="connect success" file=loggers.go func=logging.CPrint line=168 tid=40 url="ws://47.108.39.108:9029/ws"
fatal error: concurrent map writes

goroutine 7522 [running]:
runtime.throw(0xc4426f, 0x15)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc001f691d0 sp=0xc001f691a0 pc=0x43ceb2
runtime.mapassign_faststr(0xb76b60, 0xc0012785d0, 0xc0000e6ea0, 0x20, 0x16f8620)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc001f69238 sp=0xc001f691d0 pc=0x41aff1
hpool.com/dev/miner-client/miner/chain/chia.(*Miner).NewMiningInfo(0xc000136000, 0xd26e08, 0xc0003625b0, 0x0, 0x0)
	miner/chain/chia/miner.go:149 +0x2f8 fp=0xc001f69418 sp=0xc001f69238 pc=0x971f58
hpool.com/dev/miner-client/miner.(*Wrapper).Start.func1(0x5, 0xc000258259, 0x103, 0x0, 0x0, 0x0, 0x19)
	miner/wrapper_miner.go:98 +0x12d fp=0xc001f69880 sp=0xc001f69418 pc=0x99726d
hpool.com/dev/miner-client/miner/server.(*Server).MiningInfo(0xc00007c540, 0x5, 0xc000258259, 0x103, 0x0, 0x0, 0x0, 0x19)
	miner/server/server.go:36 +0x51 fp=0xc001f698c8 sp=0xc001f69880 pc=0x9904f1
hpool.com/dev/miner-client/miner/server/websocket.(*Server).connect.func1(0xc001a28840, 0xc001aa8180)
	miner/server/websocket/server.go:101 +0xc32 fp=0xc001f69fd0 sp=0xc001f698c8 pc=0x990092
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc001f69fd8 sp=0xc001f69fd0 pc=0x472fe1
created by hpool.com/dev/miner-client/miner/server/websocket.(*Server).connect
	miner/server/websocket/server.go:85 +0x4a6

goroutine 1 [chan receive, 1321 minutes]:
hpool.com/dev/miner-client/platform.Run(0xc00037bf50, 0xc00031a1e0, 0xd28758, 0xc00025ae10)
	platform/console.go:61 +0x716
main.main()
	main.go:83 +0x3de

goroutine 40 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0xc000376170, 0xc000010058)
	vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
	vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

goroutine 21 [select, 1321 minutes]:
github.com/trying2016/common-tools/utils.(*Queue).run(0xc00012c120)
	vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
	vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 125 [select, 1311 minutes]:
github.com/trying2016/common-tools/utils.(*Queue).run(0xc0005ba150)
	vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
	vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 69 [select, 1317 minutes]:
github.com/trying2016/common-tools/utils.(*Queue).run(0xc000556120)
	vendor/github.com/trying2016/common-tools/utils/queue.go:50 +0xb7
created by github.com/trying2016/common-tools/utils.(*Queue).init
	vendor/github.com/trying2016/common-tools/utils/queue.go:32 +0x125

goroutine 22 [select]:
github.com/trying2016/common-tools/utils.StartTime.func1(0x3e8, 0xc000132020, 0xc0001a4010)
	vendor/github.com/trying2016/common-tools/utils/timer.go:24 +0x9a
created by github.com/trying2016/common-tools/utils.StartTime
	vendor/github.com/trying2016/common-tools/utils/timer.go:22 +0x9b

```

<img width="1313" alt="截屏2021-05-04上午11 14 11" src="https://user-images.githubusercontent.com/23468639/116957203-dbbe0700-acc9-11eb-9fc8-f500ae86ac1c.png">

**Comment by trying2016** [comment]
v1.1.1更新过几次，已经处理过，请使用最新的软件包

**Comment by little-snow-fox** [comment]
好的
